### ISSUE TITLE
Problem with Retrieval mode.

### ISSUE THREAD

**Issue by khoa16122004** [Croissant-Team-Cinnamon-Bootcamp-2024/FinalProject#24]
I deployed your application, and it worked in internet mode. However, I'm encountering issues with retrieval mode, especially with the "search endpoint" that doesn't return any items in the result list. Additionally, I'm unsure about the purpose of the CONTEST_SEARCH_API_URL variable.

**Comment by Huy1711** [comment]
Please provide more information about how did you run the app:
1. During the build time, have you entered the code from Google account to allow video download from Youtube ?
2. Have you change the API keys inside `.env.example` to your account API keys and rename the file to `.env` ?
3. Have you added any data to the database from the Add course interface yet ? Note that only youtube playlist URL is supported (e.g. https://www.youtube.com/watch?v=jGwO_UgTS7I&list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU)

For your interest, the CONTEXT_SEARCH_API_URL environment variable is get from docker-compose.yaml file, which is the URL to the Course management service with "/search" endpoint. The "/search" endpoint of the service is defined here:
https://github.com/CroissantTeam/LlamaSensei/blob/main/app/llama_sensei/backend/add_courses/main.py#L57
The Chat service need this URL to request search function from internal Vector Database, which is inside Course management service.
